### ISSUE TITLE
Null Mastery object in MasteryPage

### ISSUE THREAD

**Issue by prefanatic** [robrua/Orianna#15]
Summoner: 19996006

NullPointerException when accessing the mastery pages of the above summoner.  Looking at the JSON response, the mastery page is named (@@!PaG3!@@35337971).

I tried reproducing by setting one of my own mastery pages to the above, but the client does not let you.  I assume thats how they internally name the pages.  Either way, the JSON response does have mastery content for this ghost page.

```
04-29 21:47:31.495  18972-20037/com.prefanatic.porosnax E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-11402
    Process: com.prefanatic.porosnax, PID: 18972
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
            at com.robrua.orianna.type.dto.summoner.MasteryPages.getMasteryIDs(MasteryPages.java:77)
            at com.robrua.orianna.api.core.SummonerAPI.getMasteryPagesByID(SummonerAPI.java:80)
            at com.robrua.orianna.api.core.SummonerAPI.getMasteryPagesByID(SummonerAPI.java:97)
            at com.robrua.orianna.api.core.SummonerAPI.getMasteryPagesByID(SummonerAPI.java:106)
            at com.robrua.orianna.api.core.SummonerAPI.getMasteryPages(SummonerAPI.java:55)
            at com.robrua.orianna.api.core.AsyncRiotAPI$63.run(AsyncRiotAPI.java:1600)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by prefanatic** [comment]
I should also point out that if a Summoner does not have any mastery points set, but does in fact have a valid mastery page, getMasteries() also returns null.  It should return an empty List<Mastery> instead.

**Comment by robrua** [comment]
I've committed a fix for the null reference. You can get the latest snapshot @ http://robrua.com/orianna/ and the change will be in the next release.

For the second comment: Do you mean masteryPage.getMasteries() is null for a page with no masteries? If so, the null value you're receiving accurately reflects the JSON payload from the API.

**Comment by prefanatic** [comment]
The second comment is what you described.  The only problem was that Orianna was crashing internally due to the null masteries, but that is no longer the case.

Thanks for the quick fix!
