### ISSUE TITLE
NullPointerException when doing summoner.getCurrentGame()

### ISSUE THREAD

**Issue by Yoplait370** [robrua/Orianna#41]
As written in title, got an exception when trying to get a summoner game.
Happens when the summoner is offline, online or in-game.
By the way, i'd like to have the proper way to get a the properties of a game (game type, duration, etc)

Here is my code : http://pastebin.com/Gh3yJNqZ
And here is the output : Exception in thread "main" java.lang.NullPointerException
	at com.robrua.orianna.type.dto.staticdata.Champion.getItemIDs(Champion.java:158)
	at com.robrua.orianna.type.dto.staticdata.ChampionList.getItemIDs(ChampionList.java:125)
	at com.robrua.orianna.api.core.StaticDataAPI.getChampions(StaticDataAPI.java:97)
	at com.robrua.orianna.api.core.StaticDataAPI.getChampionsByID(StaticDataAPI.java:134)
	at com.robrua.orianna.api.core.RiotAPI.getChampionsByID(RiotAPI.java:91)
	at com.robrua.orianna.api.core.CurrentGameAPI.getCurrentGame(CurrentGameAPI.java:24)
	at com.robrua.orianna.api.core.RiotAPI.getCurrentGame(RiotAPI.java:179)
	at com.robrua.orianna.type.core.summoner.Summoner.getCurrentGame(Summoner.java:38)
	at OriannaMain.main(OriannaMain.java:19)

Thank you in advance.

**Comment by robrua** [comment]
Hey - what version of Ori are you using? This looks a lot like a bug that I did a fix for recently, so you may just be using an old version.

**Comment by Yoplait370** [comment]
I'm using 2.3.3, will to use 2.4 the same way to see what happens.
I'll give you a feedback afterwards.
